modLoader = "javafml"
loaderVersion = "[${forge_loader_version},)"
issueTrackerURL = "https://github.com/CosmicDan-Minecraft/TemperatureBands/issues"
license = "LGPLv3"

[[mods]]
modId = "temperaturebands"
version = "${version}"
displayName = "Temperature Bands"
authors = "CosmicDan"
description = '''
Modifies world generation to place biomes into repeating temperature bands. Compatible with most worldgen mods.

https://www.curseforge.com/minecraft/mc-mods/temperaturebands
'''
logoFile = "logo.png"

[[dependencies.temperaturebands]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.temperaturebands]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.temperaturebands]]
modId = "world_preview"
mandatory = false
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"
