# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.java.home=E:/Programs/System/Java/Adoptium/jdk-21.0.4.7-hotspot

# Moved to modprops.gradle
#mod_version = 
#maven_group = 
#archives_name = 
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.19.2
java_version = 17

# CosmicDan: All these are latest for 1.19.2, as of 2026.06.29
# Via https://fabricmc.net/develop/
fabric_loader_version=0.19.3
# Via https://files.minecraftforge.net/net/minecraftforge/forge/index_1.19.2.html
forge_version = 43.5.2
forge_loader_version = 43

forgeconfigapiport_version = 4.2.11
