# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Moved to modprops.gradle
#mod_version = 
#maven_group = 
#archives_name = 
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1

# CosmicDan: All these are latest for 1.21.1, as of 2025.04.29
# From https://fabricmc.net/develop/
fabric_loader_version=0.16.14
# From https://files.minecraftforge.net/net/minecraftforge/forge/index_1.20.1.html
# NOT the latest, because 47.4.0 deprecated some config stuff for 1.21.1 (where we switch to NeoForge anyway)
neoforge_version = 21.1.213
