# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Moved to modprops.gradle
#mod_version = 
#maven_group = 
#archives_name = 
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1.2
java_version = 25

# CosmicDan: All these are latest for 26.1.2, as of 2025.06.28
# From https://fabricmc.net/develop/
fabric_loader_version=0.19.3
# Via https://neoforged.net/
neoforge_version = 26.1.2.76
neoforge_loader_version = 4

forgeconfigapiport_version = 26.1.5
