plugins {
    id 'com.gradleup.shadow'
}

apply from: '../modprops.gradle'
//base { archivesName = "$rootProject.archives_name-$project.name" }
base { archivesName = project.archives_base_name }
version = project.mod_version + "-Forge-${rootProject.minecraft_version}"
group = project.maven_group

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    forge {
        convertAccessWideners = true
        extraAccessWideners.add loom.accessWidenerPath.get().asFile.name

        mixinConfig "temperaturebands.mixins.json"
        mixinConfig "temperaturebands-forge.mixins.json"
    }
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    forge "net.minecraftforge:forge:$rootProject.minecraft_version-$rootProject.forge_version"

    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionForge')

    // MixinExtras
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.4"))
    implementation(include("io.github.llamalad7:mixinextras-forge:0.5.4"))
    
    // Caffeine library (fast LruCache) - https://github.com/ben-manes/caffeine
    forgeRuntimeLibrary("com.github.ben-manes.caffeine:caffeine:3.2.4")
    include "com.github.ben-manes.caffeine:caffeine:3.2.4"

    // World Preview (1.20.1)
    modImplementation("curse.maven:world-preview-891429:5686690")
    // Compat. testing (modded BiomeSource)
    modImplementation("curse.maven:blueprint-382216:8048579")
}

processResources {
    filesMatching('META-INF/mods.toml') {
        expand([
                version: project.mod_version,
                minecraft_version: project.minecraft_version,
                forge_version: project.forge_version,
                forge_loader_version: project.forge_loader_version
        ])
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    input.set shadowJar.archiveFile
    //Old, might still be needed...?
    //dependsOn shadowJar
    archiveClassifier = null
}

// Extras from CosmicDan, check if these are still needed...

jar {
    archiveClassifier = "dev"
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

tasks.named('build') {
    finalizedBy 'copyJar', 'copySourcesJar'
}

tasks.register('copyJar', Copy) {
    dependsOn tasks.remapJar
    from tasks.remapJar.outputs.files
    into layout.projectDirectory.dir("../build")
}

tasks.register('copySourcesJar', Copy) {
    dependsOn tasks.sourcesJar
    from tasks.sourcesJar.outputs.files
    into layout.projectDirectory.dir("../build")
}
